version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kiro-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "offersByOfferedItemId:1:1,offersByItemId:1:1,offered-items-topic:1:1,offers-topic:1:1,items-topic:1:1,item-with-offers-topic:1:1"
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: kiro-zk
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper